# Generated by Django 6.1 on 2026-09-13 04:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0007_membermodel_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberPortalInvitationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portal_invitations', to='members.membermodel')),
            ],
            options={
                'db_table': 'member_portal_invitation',
                'ordering': ['-created_at'],
            },
        ),
    ]
