# Generated by Django 6.1 on 2026-09-12 23:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0004_member_code_unique'),
        ('organizations', '0005_organizationmodel_business_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipPlanModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duration_value', models.PositiveIntegerField(default=1)),
                ('duration_unit', models.CharField(choices=[('day', 'Día'), ('week', 'Semana'), ('month', 'Mes'), ('year', 'Año')], default='month', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membership_plans', to='organizations.organizationmodel')),
            ],
            options={
                'db_table': 'membership_plan',
                'ordering': ['name'],
                'unique_together': {('organization', 'name')},
            },
        ),
        migrations.CreateModel(
            name='MemberSubscriptionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('active', 'Activa'), ('frozen', 'Congelada'), ('cancelled', 'Cancelada')], default='active', max_length=20)),
                ('frozen_since', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='members.membermodel')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_subscriptions', to='organizations.organizationmodel')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='billing.membershipplanmodel')),
            ],
            options={
                'db_table': 'member_subscription',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DuesPaymentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('method', models.CharField(choices=[('cash', 'Efectivo'), ('card', 'Tarjeta'), ('transfer', 'Transferencia'), ('other', 'Otro')], default='cash', max_length=20)),
                ('paid_at', models.DateField()),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dues_payments', to='members.membermodel')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dues_payments', to='organizations.organizationmodel')),
                ('registered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_dues_payments', to=settings.AUTH_USER_MODEL)),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='billing.membersubscriptionmodel')),
            ],
            options={
                'db_table': 'dues_payment',
                'ordering': ['-paid_at', '-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='membersubscriptionmodel',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['active', 'frozen'])), fields=('member',), name='unique_active_subscription_per_member'),
        ),
    ]
