# Generated by Django 6.1 on 2026-09-13 02:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
        ('organizations', '0006_organizationmodel_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyStatsSnapshotModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('checkins', models.PositiveIntegerField(default=0)),
                ('new_members', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_stats_snapshots', to='organizations.organizationmodel')),
            ],
            options={
                'db_table': 'daily_stats_snapshot',
                'ordering': ['date'],
                'unique_together': {('organization', 'date')},
            },
        ),
    ]
