# Generated by Django 6.1 on 2026-09-12 23:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0004_member_code_unique'),
        ('organizations', '0005_organizationmodel_business_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckInModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('code', 'Código/QR'), ('manual', 'Búsqueda manual'), ('face', 'Reconocimiento facial')], max_length=10)),
                ('checked_in_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkins', to='members.membermodel')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkins', to='organizations.organizationmodel')),
                ('registered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_checkins', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'check_in',
                'ordering': ['-checked_in_at'],
            },
        ),
    ]
