# Generated by Django 6.1 on 2026-09-13 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
        ('members', '0007_membermodel_user'),
        ('organizations', '0006_organizationmodel_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkinmodel',
            name='method',
            field=models.CharField(choices=[('code', 'Código/QR'), ('manual', 'Búsqueda manual'), ('face', 'Reconocimiento facial'), ('fingerprint', 'Huella digital')], max_length=20),
        ),
        migrations.CreateModel(
            name='BiometricDeviceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('device_key_hash', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='biometric_devices', to='organizations.organizationmodel')),
            ],
            options={
                'db_table': 'biometric_device',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MemberBiometricEnrollmentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_user_id', models.CharField(max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='attendance.biometricdevicemodel')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='biometric_enrollments', to='members.membermodel')),
            ],
            options={
                'db_table': 'member_biometric_enrollment',
                'ordering': ['-created_at'],
                'unique_together': {('device', 'external_user_id'), ('device', 'member')},
            },
        ),
    ]
