# Generated by Django 6.0.5 on 2026-05-24 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_add_members_module_to_existing_orgs'),
        ('organizations', '0004_invitationmodel_trial_payment_status'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='membermodel',
            name='unique_member_email_per_org',
        ),
        migrations.AddField(
            model_name='membermodel',
            name='member_code',
            field=models.CharField(blank=True, default='', max_length=12),
        ),
        migrations.AddField(
            model_name='membermodel',
            name='photo_url',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterUniqueTogether(
            name='membermodel',
            unique_together={('organization', 'email')},
        ),
    ]
