# Generated by Django 6.1 on 2026-09-13 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_member_code_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='membermodel',
            name='face_descriptor',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
