# Generated by Django 6.1 on 2026-09-13 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_membermodel_face_descriptor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberfieldconfigmodel',
            name='field_name',
            field=models.CharField(choices=[('id_number', 'Número de identidad'), ('address', 'Dirección'), ('birth_date', 'Fecha de nacimiento'), ('phone_secondary', 'Teléfono secundario'), ('photo', 'Foto'), ('notes', 'Notas'), ('gender', 'Género'), ('emergency_contact_name', 'Contacto de emergencia'), ('emergency_contact_phone', 'Teléfono de emergencia'), ('medical_conditions', 'Condiciones médicas / alergias'), ('goal', 'Objetivo'), ('referred_by', 'Referido por')], max_length=30),
        ),
        migrations.AlterField(
            model_name='memberstandardfieldvaluemodel',
            name='field_name',
            field=models.CharField(choices=[('id_number', 'Número de identidad'), ('address', 'Dirección'), ('birth_date', 'Fecha de nacimiento'), ('phone_secondary', 'Teléfono secundario'), ('photo', 'Foto'), ('notes', 'Notas'), ('gender', 'Género'), ('emergency_contact_name', 'Contacto de emergencia'), ('emergency_contact_phone', 'Teléfono de emergencia'), ('medical_conditions', 'Condiciones médicas / alergias'), ('goal', 'Objetivo'), ('referred_by', 'Referido por')], max_length=30),
        ),
    ]
