# Generated by Django 6.1 on 2026-09-13 00:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0005_organizationmodel_business_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('new_member', 'Nuevo socio'), ('payment_received', 'Pago registrado'), ('subscription_expiring', 'Membresía por vencer'), ('subscription_expired', 'Membresía vencida')], max_length=30)),
                ('title', models.CharField(max_length=140)),
                ('body', models.CharField(blank=True, default='', max_length=255)),
                ('link', models.CharField(blank=True, default='', max_length=200)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='organizations.organizationmodel')),
            ],
            options={
                'db_table': 'notification',
                'ordering': ['-created_at'],
            },
        ),
    ]
