# Generated by Django 6.1 on 2026-09-13 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationmodel',
            name='type',
            field=models.CharField(choices=[('new_member', 'Nuevo miembro'), ('payment_received', 'Pago registrado'), ('subscription_expiring', 'Membresía por vencer'), ('subscription_expired', 'Membresía vencida')], max_length=30),
        ),
    ]
