# Generated by Django 6.0.5 on 2026-05-16 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0002_organizationmodel_logo_url_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="organizationmodel",
            name="last_payment_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="organizationmodel",
            name="next_payment_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="organizationmodel",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("paid", "Pagado"),
                    ("unpaid", "Pendiente"),
                    ("overdue", "Vencido"),
                ],
                default="unpaid",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="organizationmodel",
            name="plan",
            field=models.CharField(
                choices=[("pro", "Pro"), ("enterprise", "Enterprise")],
                default="pro",
                max_length=20,
            ),
        ),
    ]
