# Generated by Django 6.0.5 on 2026-05-16 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="organizationmodel",
            name="logo_url",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="organizationmodel",
            name="onboarding_completed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="organizationmodel",
            name="primary_color",
            field=models.CharField(blank=True, default="", max_length=7),
        ),
        migrations.AlterField(
            model_name="organizationmodel",
            name="enabled_modules",
            field=models.JSONField(
                default=list,
                help_text="Claves de módulos habilitados: clients, payments, attendance, reports, workers",
            ),
        ),
    ]
