# Generated by Django 6.1 on 2026-09-12 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_invitationmodel_trial_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationmodel',
            name='business_type',
            field=models.CharField(choices=[('generic', 'Genérico'), ('gym', 'Gimnasio')], default='generic', help_text='Servicio/vertical contratado: determina el catálogo de módulos disponible.', max_length=20),
        ),
        migrations.AlterField(
            model_name='organizationmodel',
            name='enabled_modules',
            field=models.JSONField(default=list, help_text='Claves de módulos habilitados, acotadas al catálogo del business_type.'),
        ),
    ]
