# Generated by Django 6.1 on 2026-09-13 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0005_organizationmodel_business_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationmodel',
            name='currency',
            field=models.CharField(choices=[('COP', 'Peso colombiano (COP)'), ('USD', 'Dólar estadounidense (USD)'), ('EUR', 'Euro (EUR)'), ('MXN', 'Peso mexicano (MXN)'), ('ARS', 'Peso argentino (ARS)'), ('CLP', 'Peso chileno (CLP)'), ('PEN', 'Sol peruano (PEN)'), ('BRL', 'Real brasileño (BRL)')], default='COP', max_length=3),
        ),
    ]
