# Generated by Django 6.0.5 on 2026-05-16 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="workermodel",
            name="allowed_modules",
            field=models.JSONField(default=list),
        ),
    ]
