# Generated by Django 6.0.5 on 2026-05-24 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0002_workermodel_allowed_modules'),
    ]

    operations = [
        migrations.AddField(
            model_name='workermodel',
            name='module_permissions',
            field=models.JSONField(default=dict),
        ),
    ]
